### ISSUE TITLE
FEATURE REQ: S3, Quota Limits & Non-Invitation & Discord Embed Customizer

### ISSUE THREAD

**Issue by snaildos** [renzynx/bliss#2]
Are these possible?
Kind Regards,
Snail

**Comment by renzynx** [comment]
yes i have plan to add settings for admin to disable registration, invite mode and plan to add discord embed customizer

**Comment by snaildos** [comment]
> 

Ok, thanks!! Please keep me updated, Thanks for the reply!
Kind Regards,
Snail

**Comment by renzynx** [comment]
s3 is implemented now :D

**Comment by snaildos** [comment]
Oh and, @renzynx ,
why are you running the API and frontend on a different port? It's better to just have everything on the same service IMO.
also, how do I setup a development environment?

**Comment by renzynx** [comment]
for the first question, tbh i don't want to use nextjs custom server stuff because i can't do everything how i want with it.
and if you want to setup development environment its actually pretty simple.
just clone the repository and fill out the .env and you are good to go

**Comment by snaildos** [comment]
> for the first question, tbh i don't want to use nextjs custom server stuff because i can't do everything how i want with it. and if you want to setup development environment its actually pretty simple. just clone the repository and fill out the .env and you are good to go

then livereload? do I need to setup and install a dB as well?

**Comment by renzynx** [comment]
for the live reload just do
```shell
yarn dev
```
it will live reload both frontend and backend

personally i use docker for postgres and redis

**Comment by snaildos** [comment]
I see S3 was added, could not get it workomt, could you provide an example config? I am trying to use minio. Thanks. :)
