### ISSUE TITLE
failed to complete building 

### ISSUE THREAD

**Issue by Luxxy-GF** [renzynx/bliss#23]
hello the steps i taken on the web build is : 
yarn install
yarn build

yarn build come back with this error : 

![image](https://user-images.githubusercontent.com/68338577/164326497-3c05bb39-a4ff-4d95-a3dc-eafbfdbae5df.png)

**Comment by renzynx** [comment]
yep this is definitely my bad, i fucked up by letting renovate bot upgrading deps lmao

**Comment by Luxxy-GF** [comment]
you got a older verison ?

**Comment by renzynx** [comment]
you could wait for the dev branch to come out, i basically re-write everything because this version is kinda suck

**Comment by renzynx** [comment]
i just revert package.json back to normal, so this should be fixed

**Comment by Luxxy-GF** [comment]
yeah the building works now but i when i log in it go to dashobard for 2 secs and puts me back on the landing page

**Comment by renzynx** [comment]
it most likely because you setup the domain in .env wrong
you can dm me on discord and we will try to solve this
renzynx#7626
